### ISSUE TITLE
Can't parse date in "YYYYMMDD" format

### ISSUE THREAD

**Issue by leesharma** [fazibear/ex_ical#2]
I tried to use this tool to parse a Facebook birthday .ics file, but it failed with an argument error. Here is the format of the iCal file:

``` ical
BEGIN:VCALENDAR
... (irrelevant header stuff)
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
DTSTART:20160611
SUMMARY:Foo Bar's birthday
RRULE:FREQ=YEARLY
DURATION:P1D
UID:b000000000@facebook.com
END:VEVENT
...
END:VCALENDAR
```

This is the full text of the error:

``` iex
** (ArgumentError) argument error
     (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
              lib/tzdata/release_reader.ex:41: Tzdata.ReleaseReader.current_release_from_table/0
              lib/tzdata/release_reader.ex:13: Tzdata.ReleaseReader.simple_lookup/1
              lib/tzdata/release_reader.ex:7: Tzdata.ReleaseReader.zone_and_link_list/0
              lib/tzdata.ex:61: Tzdata.zone_exists?/1
              lib/timezone/timezone.ex:130: Timex.Timezone.get/2
    (ex_ical) lib/ex_ical/date_parser.ex:23: ExIcal.DateParser.parse/2
    (ex_ical) lib/ex_ical/parser.ex:12: ExIcal.Parser.parse_line/2
```
- [lib/ex_ical/date_parser.ex:23](https://github.com/fazibear/ex_ical/blob/master/lib/ex_ical/date_parser.ex#L23)
- [lib/ex_ical/parser.ex:12](https://github.com/fazibear/ex_ical/blob/master/lib/ex_ical/parser.ex#L12)

Following the stack trace, it looks like there's no pattern for the `YYYYMMDD` input string with a timezone of `nil`. When `DateParser` tried to parse `DTSTART`, it tried to pass `nil` to `Timezone.get/1`, throwing an argument error.

This looks like it won't be a hard fix; I'll open a pull request with the bugfix/tests.

**Comment by leesharma** [comment]
Also, I did see the open pull request (#1), but it looks like it doesn't address this bug–the argument error occurs with that code as well.

**Comment by fazibear** [comment]
Thanks! 👍

**Comment by leesharma** [comment]
Could you use any help getting this library to 1.0? I'll need to work with some ical files soon, and I figure it's better to help an existing library instead of starting something new.

**Comment by fazibear** [comment]
Right now I'm using ruby to parse ical files. Wrote this one, but for now timezones are broken. So I'll release a version with your changes, but just as I said, version 1.0 should works fine with timezones, google calendar use them a lot.
